default_platform(:android)

platform :android do
  desc "Run tests and build debug APK for CI"
  lane :ci do
    gradle(task: "clean")
    gradle(task: "test")
    gradle(task: "assembleDebug")
  end

  desc "Build release APK"
  lane :release_build do
    gradle(task: "clean")
    gradle(task: "assembleRelease")
  end
end
